#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# config/routes.yaml

hello_the_world:
    path:       /hello-world
    controller: App\Controller\AdvertController::index